import { Space_Grotesk, Inter, JetBrains_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-display",
  display: "swap",
});
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-body",
  display: "swap",
});
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
  display: "swap",
});

const SITE_URL = "https://rizkyirawan.rcl.biz.id"; // ganti dengan domain asli saat deploy

export const metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Rizky Irawan — Web Developer",
    template: "%s | Rizky Irawan",
  },
  description:
    "Rizky Irawan — Web Developer. Crafting professional digital solutions, one pixel at a time. Spesialis responsive web design, WhatsApp bot automation, dan UI/UX prototyping.",
  keywords: [
    "Rizky Irawan",
    "Web Developer",
    "Rizky Developer",
    "Rizky Irawan Portofolio", 
    "Portofolio Rizky Irawan", 
    "Rizky Irawan Lampung Tengah", 
    "Rizky Irawan Lamteng", 
    "Rizky Irawan mts", 
    "Siapakah Rizky Irawan", 
    "Siapa Rizky Irawan", 
    "Rizky Irawan Developer", 
    "Rizky", 
    "Web Developer Lampung",
    "Frontend Developer Indonesia",
    "WhatsApp Bot Developer",
    "Portfolio Web Developer",
    "Rizky Irawan portfolio",
    "website Rizky Irawan",
    "Rizky Irawan official",
    "Rizky Irawan personal website",
    "profil Rizky Irawan",
    "tentang Rizky Irawan",
    "Rizky Irawan resume",
    "Rizky Irawan CV",
    "Rizky Irawan kontak",
    "Rizky Irawan karya",
    "Rizky Irawan proyek",
    "Rizky Irawan project",
    "Rizky Irawan work",
    "Rizky Irawan designer",
    "Rizky Irawan graphic designer",
    "Rizky Irawan UI UX",
    "Rizky Irawan web developer",
    "Rizky Irawan programmer",
    "Rizky Irawan software engineer",
    "Rizky Irawan frontend developer",
    "Rizky Irawan fullstack",
    "Rizky Irawan app developer",
    "Rizky Irawan video editor",
    "Rizky Irawan content creator",
    "Rizky Irawan digital creator",
    "Rizky Irawan creative",
    "Rizky Irawan illustrator",
    "Rizky Irawan 3D artist",
    "Rizky Irawan animator",
    "Rizky Irawan freelancer",
    "Rizky Irawan Indonesia",
    "jasa Rizky Irawan",
    "layanan Rizky Irawan",
    "hire Rizky Irawan",
    "sewa Rizky Irawan",
    "desain oleh Rizky Irawan",
    "project Rizky Irawan terbaru",
    "portofolio desain Rizky Irawan",
    "portofolio developer Rizky Irawan",
    "portofolio pemrograman Rizky Irawan",
    "portofolio kreatif Rizky Irawan",
    "Rizky Irawan profesional",
    "Rizky Irawan spesialis",
    "Rizky Irawan konsultan",
    "Rizky Irawan github",
    "Rizky Irawan linkedin",
    "Rizky Irawan behance",
    "Rizky Irawan dribbble",
    "Rizky Irawan instagram",
    "Rizky Irawan bio",
    "situs resmi Rizky Irawan",
    "link portofolio Rizky Irawan",
    "kumpulan proyek Rizky Irawan",
    "Rizky Irawan showcase",
    "Rizky Irawan web",
    "Rizky Irawan bot developer",
    "Rizky Irawan JS developer",
    "Rizky Irawan nodejs",
    "Rizky Irawan react",
    "Rizky Irawan backend",
    "jasa web developer Lampung",
    "jasa bikin bot WhatsApp",
    "developer bot WA Lampung",
    "frontend developer Lampung",
    "web developer Lampung Tengah",
    "freelance web developer Lampung",
    "jasa pembuatan website Rizky Irawan",
    "Rizky Irawan code",
    "Rizky Irawan coder",
    "Rizky Irawan tech",
    "Rizky Irawan IT",
    "Rizky Irawan script",
    "Rizky Irawan source code",
    "Rizky Irawan repository",
    "Rizky Irawan contact",
    "Rizky Irawan email",
    "Rizky Irawan social media",
    "Rizky Irawan achievements",
    "Rizky Irawan experience",
    "Rizky Irawan skills",
    "Rizky Irawan biography",
    "Rizky Irawan profile page",
    "Rizky Irawan main page",
    "Rizky Irawan landing page",
    "Rizky Irawan site",
    "Rizky Irawan web page",
    "Rizky Irawan home",
    "Rizky Irawan web master",
    "Rizky Irawan fullstack developer",
    "Rizky Irawan backend developer",
    "Rizky Irawan JavaScript",
    "Rizky Irawan Python",
    "Rizky Irawan HTML CSS",
    "Rizky Irawan React developer",
    "Rizky Irawan Vue developer",
    "Rizky Irawan Tailwind",
    "Rizky Irawan Node JS",
    "Rizky Irawan Firebase",
    "Rizky Irawan Next JS",
    "Rizky Irawan API developer",
    "Rizky Irawan Rest API",
    "Rizky Irawan Express JS",
    "Rizky Irawan PHP developer",
    "Rizky Irawan Laravel developer",
    "Rizky Irawan Database",
    "Rizky Irawan MySQL",
    "Rizky Irawan MongoDB",
    "Rizky Irawan Git",
    "Rizky Irawan GitHub profile",
    "Rizky Irawan Vercel",
    "Rizky Irawan Netlify",
    "Rizky Irawan WhatsApp automation",
    "Rizky Irawan WA Bot JS",
    "Rizky Irawan Bot creator",
    "Rizky Irawan script bot",
    "Rizky Irawan Baileys Bot",
    "Rizky Irawan Telegram Bot",
    "Rizky Irawan Discord Bot",
    "Rizky Irawan Automation",
    "Rizky Irawan UI UX designer",
    "Rizky Irawan Figma",
    "Rizky Irawan poster designer",
    "Rizky Irawan Alight Motion",
    "Rizky Irawan video creator",
    "Rizky Irawan banner design",
    "Rizky Irawan design portfolio",
    "Rizky Irawan Block coding",
    "Rizky Irawan Blockly",
    "Rizky Irawan app project",
    "Rizky Irawan mobile developer",
    "Rizky Irawan Flutter",
    "Rizky Irawan React Native",
    "Rizky Irawan APK",
    "Rizky Irawan Web App",
    "Rizky Irawan PWA",
    "Rizky Irawan SEO specialist",
    "Rizky Irawan Web designer",
    "Rizky Irawan Web engineer",
    "jasa pembuatan bot WA",
    "jasa bikin bot WhatsApp Lampung",
    "jasa website portofolio",
    "jasa pembuatan website Lampung",
    "jasa buat web murah Lampung",
    "jasa landing page Lampung",
    "jasa frontend developer Indonesia",
    "jasa bot automation WA",
    "jasa kustom bot WhatsApp",
    "jasa integrasi API WhatsApp",
    "jasa slicing Figma ke HTML",
    "jasa slicing Figma ke React",
    "jasa buat web landing page",
    "jasa buat website pribadi",
    "jasa maintenance website",
    "jasa redesign website",
    "web developer Sumatera",
    "web developer Sumatra Selatan",
    "programmer Lampung Tengah",
    "developer muda Indonesia",
    "jasa programmer freelance Lampung",
    "jasa web developer terdekat",
    "hire frontend developer Indonesia",
    "hire bot developer Indonesia",
    "freelance programmer Lampung",
    "freelance bot developer",
    "freelance web developer terdekat",
    "portofolio web developer Indonesia",
    "portofolio bot whatsapp",
    "portofolio frontend developer",
    "contoh portofolio web developer",
    "website portofolio Rizky Irawan",
    "galeri proyek Rizky Irawan",
   "showcase proyek Rizky Irawan",
    "situs portofolio Rizky Irawan",
    "laman resmi Rizky Irawan",
    "kontak bisnis Rizky Irawan",
    "email bisnis Rizky Irawan",
    "layanan digital Rizky Irawan",
    "solusi web Rizky Irawan",
    "solusi automation Rizky Irawan",
    "Rizky Irawan profile",
    "jasa web developer Rizky Irawan",
    "jasa pembuatan website",
    "jasa buat website",
    "jasa bikinkan website",
    "jasa pembuat website",
    "jasa website profesional",
    "jasa website murah",
    "jasa landing page",
    "jasa buat landing page",
    "jasa bikin landing page",
    "jasa website UMKM",
    "jasa website perusahaan",
    "jasa website toko online",
    "jasa website custom",
    "jasa website responsif",
    "jasa perbaikan website",
    "jasa pengembang web",
    "jasa fullstack developer",
    "jasa programmer website",
    "jasa pembuatan web app",
    "jasa web application",
    "jasa backend website",
    "jasa frontend website",
    "jasa sistem informasi web",
    "jasa pembuatan website Lampung Tengah",
    "jasa website Lampung",
    "jasa web developer Indonesia",
    "jasa pembuat website terdekat",
    "jasa buat web terdekat",
    "fullstack developer Indonesia",
    "fullstack developer Lampung",
    "web developer Lampung",
    "programmer Lampung",
    "freelance fullstack developer",
    "freelance programmer Indonesia",
    "hire fullstack developer",
    "hire web developer Indonesia",
    "hire programmer Indonesia",
    "sewa jasa web developer",
    "sewa programmer website", 
    "rizky",
    "irawan",
    "portofolio",
    "portfolio",
    "fullstack",
    "full stack",
    "developer",
    "programmer",
    "coder",
    "engineer",
    "web",
    "website",
    "freelancer",
    "freelance",
    "jasamurah",
    "jasaweb",
    "bikinweb",
    "buatweb",
    "botwa",
    "wabot",
    "rizky dev",
    "irawan dev",
    "rizky code",
    "irawan code",
    "rizky tech",
    "irawan tech",
    "rizky web",
    "irawan web",
    "rizky site",
    "irawan site",
    "rizky work",
    "irawan work",
    "fullstack dev",
    "fullstack programmer",
    "fullstack engineer",
    "web dev",
    "web programmer",
    "web engineer",
    "web designer",
    "app dev",
    "app programmer",
    "bot dev",
    "automation dev",
    "script dev",
    "portofolio web",
    "portofolio dev",
    "portofolio programmer",
    "portofolio coder",
    "portofolio engineer",
    "portofolio fullstack",
    "portofolio frontend",
    "portofolio backend",
    "portofolio digital",
    "portofolio karya",
    "portofolio proyek",
    "portofolio project",
    "portofolio showcase",
    "portofolio personal",
    "portofolio online",
    "portfolio web",
    "portfolio dev",
    "portfolio programmer",
    "portfolio fullstack",
    "portfolio designer",
    "jasa web",
    "jasa website",
    "jasa landing page",
    "jasa pembuatan web",
    "jasa buat web",
    "jasa bikin web",
    "jasa pembuat web",
    "jasa programmer",
    "jasa developer",
    "jasa fullstack",
    "jasa frontend",
    "jasa backend",
    "jasa bot",
    "jasa script",
    "jasa kustom web",
    "jasa web murah",
    "jasa web profesional",
    "jasa web umkm",
    "jasa web perusahaan",
    "jasa web toko online",
    "jasa web custom",
    "jasa web landing page",
    "jasa web terdekat",
    "jasa web id",
    "bikin website",
    "buat website",
    "pembuatan website",
    "pembuat website",
    "pengembang website",
    "pengembang web",
    "situs pribadi",
    "situs portofolio",
    "situs resmi",
    "web pribadi",
    "web portofolio",
    "web profesional",
    "web resume",
    "web cv",
    "landing page",
    "landing page murah",
    "landing page profesional",
    "web app",
    "web application",
    "frontend",
    "backend",
    "fullstack indonesia",
    "programmer indonesia",
    "web dev indonesia",
    "developer indonesia",
    "freelancer indonesia",
    "programmer lampung",
    "web dev lampung",
    "developer lampung",
    "freelancer lampung",
    "jasa web lampung",
    "hire programmer",
    "hire developer",
    "hire fullstack",
    "hire web dev",
    "sewa programmer",
    "sewa developer",
    "sewa web dev",
    "cari programmer",
    "cari developer",
    "cari pembuat website"
    
  ],
  authors: [{ name: "Rizky Irawan" }],
  creator: "Rizky Irawan",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "id_ID",
    url: SITE_URL,
    siteName: "Rizky Irawan — Web Developer",
    title: "Rizky Irawan — Web Developer",
    description:
      "Crafting professional digital solutions, one pixel at a time. Lihat proyek, skill, dan cara menghubungi Rizky Irawan.",
    images: [
      {
        url: "/assets/52823.png",
        width: 1593,
        height: 1137,
        alt: "Rizky Developer",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Rizky Irawan — Web Developer",
    description: "Crafting professional digital solutions, one pixel at a time.",
    images: ["/assets/52823.png"],
  },
  alternates: {
    canonical: SITE_URL,
  },
};

function JsonLd() {
  const data = {
    "@context": "https://schema.org",
    "@type": "Person",
    name: "Rizky Irawan",
    url: SITE_URL,
    image: `${SITE_URL}/assets/52824.jpg`,
    jobTitle: "Web Developer",
    description:
      "Web Developer yang berfokus pada pengembangan digital experience, responsive web design, dan otomasi WhatsApp bot.",
    address: {
      "@type": "PostalAddress",
      addressRegion: "Lampung Tengah",
      addressCountry: "ID",
    },
    email: "mailto:zkyeea@gmail.com",
    sameAs: [
      "https://instagram.com/air_minerall7",
      "https://tiktok.com/zkyyyy077",
    ],
    knowsAbout: [
      "HTML",
      "JavaScript",
      "CSS",
      "Python",
      "GitHub",
      "Java",
      "MySQL",
      "PHP",
      "C++",
    ],
  };

  return (
    <script
      type="application/ld+json"
      // JSON di sini murni data statis milik kita sendiri (bukan HTML dari
      // input user), jadi aman dipakai bersama dangerouslySetInnerHTML.
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="id"
      suppressHydrationWarning
      className={`${spaceGrotesk.variable} ${inter.variable} ${jetbrainsMono.variable}`}
    >
      <head>
        <JsonLd />
      </head>
      <body suppressHydrationWarning>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
